### ISSUE TITLE
[Suggestion] Website Footer

### ISSUE THREAD

**Issue by he7yz** [ZaCodeHkm/Habitopia#62]
where da footer for contact :<
i had to go thru the project proposal just to find your repo :C

**Why?**
Coz good websites would atleast have some footer information, such as

- Contact Information (so tat users can help you find bugs, give suggestions or feedback, etc.)
- Copyright Info (just the year would be enough to notify the user it's latest year of update)

if u wanna kno more then feel free to check this [article](https://northstreetcreative.com/notes/why-is-your-website-footer-important/), veri quite helpful yes

Example: 
![image](https://github.com/user-attachments/assets/2b0b5ae6-61a8-4cc1-b835-996aa29a4add)
(i went to their repo aswell :3)

**Comment by ZaCodeHkm** [comment]
thanks for the suggestion shaz, its a good one. we'll add it sometime this week

**Comment by nattprog** [comment]
isn't there a mail button?

**Comment by he7yz** [comment]
no probs :D

**Comment by DivineRhythm** [comment]
done

**Comment by he7yz** [comment]
tanks shawn!!
